=== rafaelgonzalezfrancisco/IFCD0210/MF0491-3 CLIENTE/UF1842/E4/xsd-dtd/equiposdefutbol.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generado con XMLSpy v2019 rel. 3 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ciudad">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Albacete"/>
				<xs:enumeration value="Las Palmas de Gran Canaria"/>
				<xs:enumeration value="S/C de Tenerife"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="datos">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI">
				<xs:enumeration value="https://www.laliga.es/jugador/a-arroyo"/>
				<xs:enumeration value="https://www.laliga.es/jugador/acuna"/>
				<xs:enumeration value="https://www.laliga.es/jugador/alberto"/>
				<xs:enumeration value="https://www.laliga.es/jugador/araujo"/>
				<xs:enumeration value="https://www.laliga.es/jugador/ballou-tabla"/>
				<xs:enumeration value="https://www.laliga.es/jugador/cala"/>
				<xs:enumeration value="https://www.laliga.es/jugador/camille"/>
				<xs:enumeration value="https://www.laliga.es/jugador/caro-1"/>
				<xs:enumeration value="https://www.laliga.es/jugador/dani-hernandez"/>
				<xs:enumeration value="https://www.laliga.es/jugador/daniel-torres"/>
				<xs:enumeration value="https://www.laliga.es/jugador/david-garcia-s"/>
				<xs:enumeration value="https://www.laliga.es/jugador/de-la-bella"/>
				<xs:enumeration value="https://www.laliga.es/jugador/deivid"/>
				<xs:enumeration value="https://www.laliga.es/jugador/eugeni"/>
				<xs:enumeration value="https://www.laliga.es/jugador/fran-garcia"/>
				<xs:enumeration value="https://www.laliga.es/jugador/hector-hernandez"/>
				<xs:enumeration value="https://www.laliga.es/jugador/javi-castellano"/>
				<xs:enumeration value="https://www.laliga.es/jugador/luis-perez"/>
				<xs:enumeration value="https://www.laliga.es/jugador/malbasic"/>
				<xs:enumeration value="https://www.laliga.es/jugador/milla-1"/>
				<xs:enumeration value="https://www.laliga.es/jugador/nano-1"/>
				<xs:enumeration value="https://www.laliga.es/jugador/nicolas-gorosito"/>
				<xs:enumeration value="https://www.laliga.es/jugador/p228611-28917180704"/>
				<xs:enumeration value="https://www.laliga.es/jugador/paco-montanes"/>
				<xs:enumeration value="https://www.laliga.es/jugador/penalba"/>
				<xs:enumeration value="https://www.laliga.es/jugador/raul"/>
				<xs:enumeration value="https://www.laliga.es/jugador/roman-zozulya"/>
				<xs:enumeration value="https://www.laliga.es/jugador/ruben-castro"/>
				<xs:enumeration value="https://www.laliga.es/jugador/ruiz-de-galarreta"/>
				<xs:enumeration value="https://www.laliga.es/jugador/santiago-gentiletti"/>
				<xs:enumeration value="https://www.laliga.es/jugador/slavoljub-srnic"/>
				<xs:enumeration value="https://www.laliga.es/jugador/sulley-muntari"/>
				<xs:enumeration value="https://www.laliga.es/jugador/susaeta-1"/>
				<xs:enumeration value="https://www.laliga.es/jugador/suso-santana"/>
				<xs:enumeration value="https://www.laliga.es/jugador/tomas-pekhart"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="equipo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ciudad"/>
				<xs:element ref="estadio"/>
				<xs:element ref="socios"/>
				<xs:element ref="jugadores"/>
			</xs:sequence>
			<xs:attribute name="nomequi" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Albacete Balompié SAD"/>
						<xs:enumeration value="CD Tenerife"/>
						<xs:enumeration value="UD Las Palmas"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="equiposdefutbol">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equipo" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="estadio">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Carlos Belmonte"/>
				<xs:enumeration value="Estadio de Gran Canaria"/>
				<xs:enumeration value="Heliodoro Rodríguez López"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="foto">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="acuna.jpg"/>
				<xs:enumeration value="alberto.jpg"/>
				<xs:enumeration value="araujo.jpg"/>
				<xs:enumeration value="arroyo.jpg"/>
				<xs:enumeration value="ballou.jpg"/>
				<xs:enumeration value="caro.jpg"/>
				<xs:enumeration value="dani.jpg"/>
				<xs:enumeration value="danitorres.jpg"/>
				<xs:enumeration value="david.jpg"/>
				<xs:enumeration value="davidomar.jpg"/>
				<xs:enumeration value="eugeni.jpg"/>
				<xs:enumeration value="filip.jpg"/>
				<xs:enumeration value="francisco.jpg"/>
				<xs:enumeration value="gabriel.jpg"/>
				<xs:enumeration value="gentileti.jpg"/>
				<xs:enumeration value="gorosito.jpg"/>
				<xs:enumeration value="hector.jpg"/>
				<xs:enumeration value="inigoruiz.jpg"/>
				<xs:enumeration value="javicastellano.jpg"/>
				<xs:enumeration value="josemanuel.jpg"/>
				<xs:enumeration value="juantorres.jpg"/>
				<xs:enumeration value="luismilla.jpg"/>
				<xs:enumeration value="luisperez.jpg"/>
				<xs:enumeration value="muntari.jpg"/>
				<xs:enumeration value="nano.jpg"/>
				<xs:enumeration value="raul.jpg"/>
				<xs:enumeration value="roman.jpg"/>
				<xs:enumeration value="rubencastro.jpg"/>
				<xs:enumeration value="samuel.jpg"/>
				<xs:enumeration value="slavol.jpg"/>
				<xs:enumeration value="susaeta.jpg"/>
				<xs:enumeration value="susosantana.jpg"/>
				<xs:enumeration value="tomas.jpg"/>
				<xs:enumeration value="uros.jpg"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="jugador">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="nacionalidad"/>
				<xs:element ref="foto"/>
				<xs:element ref="datos"/>
			</xs:sequence>
			<xs:attribute name="equi" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="albacete"/>
						<xs:enumeration value="laspalmas"/>
						<xs:enumeration value="tenerife"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="posicion" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="centrocampista"/>
						<xs:enumeration value="defensa"/>
						<xs:enumeration value="delantero"/>
						<xs:enumeration value="portero"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="jugadores">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="jugador" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nacionalidad">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="argentina"/>
				<xs:enumeration value="colombiana"/>
				<xs:enumeration value="española"/>
				<xs:enumeration value="francesa"/>
				<xs:enumeration value="italana"/>
				<xs:enumeration value="servia"/>
				<xs:enumeration value="venezolana"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="nombre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=" Juan Gentiletti "/>
				<xs:enumeration value="Alberto Jiménez"/>
				<xs:enumeration value="Alberto de la Bella"/>
				<xs:enumeration value="Alexander Mesa"/>
				<xs:enumeration value="Ballou Jean-Yves"/>
				<xs:enumeration value="Daniel Hernández"/>
				<xs:enumeration value="Daniel Torres Rojas"/>
				<xs:enumeration value="David García Santana"/>
				<xs:enumeration value="David Omar Rodríguez"/>
				<xs:enumeration value="Eugeni Valderrama"/>
				<xs:enumeration value="Ezequiel Araujo"/>
				<xs:enumeration value="Ezequiel Gorosito"/>
				<xs:enumeration value="Filip Malbašić"/>
				<xs:enumeration value="Francisco García"/>
				<xs:enumeration value="Francisco Montañés"/>
				<xs:enumeration value="Gabriel Martín"/>
				<xs:enumeration value="Héctor Hernández"/>
				<xs:enumeration value="Iñigo Ruiz de Galarreta"/>
				<xs:enumeration value="Javi Castellano"/>
				<xs:enumeration value="Javier Acuña Caballero"/>
				<xs:enumeration value="Jesús Manuel Santana"/>
				<xs:enumeration value="José Antonio Caro"/>
				<xs:enumeration value="José Manuel García"/>
				<xs:enumeration value="Juan Torres Ruiz"/>
				<xs:enumeration value="Luis Jesús Pérez"/>
				<xs:enumeration value="Luis Milla Manzanilla"/>
				<xs:enumeration value="Néstor Susaeta"/>
				<xs:enumeration value="Raúl Fernández"/>
				<xs:enumeration value="Roman Zozulia"/>
				<xs:enumeration value="Rubén Castro"/>
				<xs:enumeration value="Samuel Geoffroy"/>
				<xs:enumeration value="Slavoljub Srnić"/>
				<xs:enumeration value="Sulleyman Muntari"/>
				<xs:enumeration value="Tomas Pekhart"/>
				<xs:enumeration value="Uroš Račić Lesct"/>
				<xs:enumeration value="Álvaro Arroyo"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="socios">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:enumeration value="13.856"/>
				<xs:enumeration value="15.49"/>
				<xs:enumeration value="18.456"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== rafaelgonzalezfrancisco/IFCD0210/MF0491-3 CLIENTE/UF1841/E2/equiposdefutbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./xsl/equiposdefutbol.xsl"?>
<equiposdefutbol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Alumnos/Documents/practica%20E2/xsd-dtd/equiposdefutbol.xsd">
	<equipo nomequi="CD Tenerife">
		<ciudad>S/C de Tenerife</ciudad>
		<estadio>Heliodoro Rodríguez López</estadio>
		<socios>13.856</socios>
		<jugadores>
			<jugador equi="tenerife" posicion="portero">
				<nombre>Daniel Hernández</nombre>
				<nacionalidad>venezolana</nacionalidad>
				<foto>dani.jpg</foto>
				<datos>https://www.laliga.es/jugador/dani-hernandez</datos>
			</jugador>
			<jugador equi="tenerife" posicion="defensa">
				<nombre>Luis Jesús Pérez</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>luisperez.jpg</foto>
				<datos>https://www.laliga.es/jugador/luis-perez</datos>
			</jugador>
			<jugador equi="tenerife" posicion="defensa">
				<nombre>Héctor Hernández</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>hector.jpg</foto>
				<datos>https://www.laliga.es/jugador/hector-hernandez</datos>
			</jugador>
			<jugador equi="tenerife" posicion="defensa">
				<nombre>Samuel Geoffroy</nombre>
				<nacionalidad>francesa</nacionalidad>
				<foto>samuel.jpg</foto>
				<datos>https://www.laliga.es/jugador/camille</datos>
			</jugador>
			<jugador equi="tenerife" posicion="defensa">
				<nombre>Alberto Jiménez</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>alberto.jpg</foto>
				<datos>https://www.laliga.es/jugador/alberto</datos>
			</jugador>
			<jugador equi="tenerife" posicion="centrocampista">
				<nombre>Luis Milla Manzanilla</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>luismilla.jpg</foto>
				<datos>https://www.laliga.es/jugador/milla-1</datos>
			</jugador>
			<jugador equi="tenerife" posicion="centrocampista">
				<nombre>Jesús Manuel Santana</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>susosantana.jpg</foto>
				<datos>https://www.laliga.es/jugador/suso-santana</datos>
			</jugador>
			<jugador equi="tenerife" posicion="centrocampista">
				<nombre>Uroš Račić Lesct</nombre>
				<nacionalidad>servia</nacionalidad>
				<foto>uros.jpg</foto>
				<datos>https://www.laliga.es/jugador/p228611-28917180704</datos>
			</jugador>
			<jugador equi="tenerife" posicion="centrocampista">
				<nombre>Francisco Montañés</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>francisco.jpg</foto>
				<datos>https://www.laliga.es/jugador/paco-montanes</datos>
			</jugador>
			<jugador equi="tenerife" posicion="delantero">
				<nombre>Filip Malbašić</nombre>
				<nacionalidad>servia</nacionalidad>
				<foto>filip.jpg</foto>
				<datos>https://www.laliga.es/jugador/malbasic</datos>
			</jugador>
			<jugador equi="tenerife" posicion="delantero">
				<nombre>José Manuel García</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>josemanuel.jpg</foto>
				<datos>https://www.laliga.es/jugador/malbasic</datos>
			</jugador>
			<jugador equi="tenerife" posicion="delantero">
				<nombre>Alexander Mesa</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>nano.jpg</foto>
				<datos>https://www.laliga.es/jugador/nano-1</datos>
			</jugador>
		</jugadores>
	</equipo>
	<equipo nomequi="UD Las Palmas">
		<ciudad>Las Palmas de Gran Canaria</ciudad>
		<estadio>Estadio de Gran Canaria</estadio>
		<socios>18.456</socios>
		<jugadores>
			<jugador equi="laspalmas" posicion="portero">
				<nombre>Raúl Fernández</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>raul.jpg</foto>
				<datos>https://www.laliga.es/jugador/raul</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="defensa">
				<nombre>Alberto de la Bella</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>alberto.jpg</foto>
				<datos>https://www.laliga.es/jugador/de-la-bella</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="defensa">
				<nombre>David García Santana</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>david.jpg</foto>
				<datos>https://www.laliga.es/jugador/david-garcia-s</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="defensa">
				<nombre>David Omar Rodríguez</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>davidomar.jpg</foto>
				<datos>https://www.laliga.es/jugador/deivid</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="defensa">
				<nombre>Juan Torres Ruiz</nombre>
				<nacionalidad>colombiana</nacionalidad>
				<foto>juantorres.jpg</foto>
				<datos>https://www.laliga.es/jugador/cala</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="centrocampista">
				<nombre>Javi Castellano</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>javicastellano.jpg</foto>
				<datos>https://www.laliga.es/jugador/javi-castellano</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="centrocampista">
				<nombre>Iñigo Ruiz de Galarreta</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>inigoruiz.jpg</foto>
				<datos>https://www.laliga.es/jugador/ruiz-de-galarreta</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="centrocampista">
				<nombre>Slavoljub Srnić</nombre>
				<nacionalidad>servia</nacionalidad>
				<foto>slavol.jpg</foto>
				<datos>https://www.laliga.es/jugador/slavoljub-srnic</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="centrocampista">
				<nombre>Gabriel Martín</nombre>
				<nacionalidad>argentina</nacionalidad>
				<foto>gabriel.jpg</foto>
				<datos>https://www.laliga.es/jugador/penalba</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="delantero">
				<nombre>Rubén Castro</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>rubencastro.jpg</foto>
				<datos>https://www.laliga.es/jugador/ruben-castro</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="delantero">
				<nombre>Tomas Pekhart</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>tomas.jpg</foto>
				<datos>https://www.laliga.es/jugador/tomas-pekhart</datos>
			</jugador>
			<jugador equi="laspalmas" posicion="delantero">
				<nombre>Ezequiel Araujo</nombre>
				<nacionalidad>argentina</nacionalidad>
				<foto>araujo.jpg</foto>
				<datos>https://www.laliga.es/jugador/araujo</datos>
			</jugador>
		</jugadores>
	</equipo>
	<equipo nomequi="Albacete Balompié SAD">
		<ciudad>Albacete</ciudad>
		<estadio>Carlos Belmonte</estadio>
		<socios>15.490</socios>
		<jugadores>
			<jugador equi="albacete" posicion="portero">
				<nombre>José Antonio Caro</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>caro.jpg</foto>
				<datos>https://www.laliga.es/jugador/caro-1</datos>
			</jugador>
			<jugador equi="albacete" posicion="defensa">
				<nombre>Álvaro Arroyo</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>arroyo.jpg</foto>
				<datos>https://www.laliga.es/jugador/a-arroyo</datos>
			</jugador>
			<jugador equi="albacete" posicion="defensa">
				<nombre>Francisco García</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>francisco.jpg</foto>
				<datos>https://www.laliga.es/jugador/fran-garcia</datos>
			</jugador>
			<jugador equi="albacete" posicion="defensa">
				<nombre>Ezequiel Gorosito</nombre>
				<nacionalidad>argentina</nacionalidad>
				<foto>gorosito.jpg</foto>
				<datos>https://www.laliga.es/jugador/nicolas-gorosito</datos>
			</jugador>
			<jugador equi="albacete" posicion="defensa">
				<nombre> Juan Gentiletti </nombre>
				<nacionalidad>italana</nacionalidad>
				<foto>gentileti.jpg</foto>
				<datos>https://www.laliga.es/jugador/santiago-gentiletti</datos>
			</jugador>
			<jugador equi="albacete" posicion="centrocampista">
				<nombre>Sulleyman Muntari</nombre>
				<nacionalidad>francesa</nacionalidad>
				<foto>muntari.jpg</foto>
				<datos>https://www.laliga.es/jugador/sulley-muntari</datos>
			</jugador>
			<jugador equi="albacete" posicion="centrocampista">
				<nombre>Néstor Susaeta</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>susaeta.jpg</foto>
				<datos>https://www.laliga.es/jugador/susaeta-1</datos>
			</jugador>
			<jugador equi="albacete" posicion="centrocampista">
				<nombre>Eugeni Valderrama</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>eugeni.jpg</foto>
				<datos>https://www.laliga.es/jugador/eugeni</datos>
			</jugador>
			<jugador equi="albacete" posicion="centrocampista">
				<nombre>Daniel Torres Rojas</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>danitorres.jpg</foto>
				<datos>https://www.laliga.es/jugador/daniel-torres</datos>
			</jugador>
			<jugador equi="albacete" posicion="delantero">
				<nombre>Ballou Jean-Yves</nombre>
				<nacionalidad>francesa</nacionalidad>
				<foto>ballou.jpg</foto>
				<datos>https://www.laliga.es/jugador/ballou-tabla</datos>
			</jugador>
			<jugador equi="albacete" posicion="delantero">
				<nombre>Roman Zozulia</nombre>
				<nacionalidad>argentina</nacionalidad>
				<foto>roman.jpg</foto>
				<datos>https://www.laliga.es/jugador/roman-zozulya</datos>
			</jugador>
			<jugador equi="albacete" posicion="delantero">
				<nombre>Javier Acuña Caballero</nombre>
				<nacionalidad>española</nacionalidad>
				<foto>acuna.jpg</foto>
				<datos>https://www.laliga.es/jugador/acuna</datos>
			</jugador>
		</jugadores>
	</equipo>
</equiposdefutbol>
