=== rafaelgonzalezfrancisco/IFCD0210/MF0491-3 CLIENTE/UF1841/E2/equiposdefutbol.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generado con XMLSpy v2019 rel. 3 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ciudad">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Albacete"/>
				<xs:enumeration value="Las Palmas de Gran Canaria"/>
				<xs:enumeration value="S/C de Tenerife"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="equipo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="ciudad"/>
				<xs:element ref="jugadores"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="equiposdefutbol">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equipo" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="jugador">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="nacionalidad"/>
			</xs:sequence>
			<xs:attribute name="posicion" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="centrocampista"/>
						<xs:enumeration value="defensa"/>
						<xs:enumeration value="delantero"/>
						<xs:enumeration value="portero"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="jugadores">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="jugador" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nacionalidad">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="argentina"/>
				<xs:enumeration value="colombiana"/>
				<xs:enumeration value="española"/>
				<xs:enumeration value="francesa"/>
				<xs:enumeration value="italana"/>
				<xs:enumeration value="servia"/>
				<xs:enumeration value="venezolana"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="nombre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=" Juan Gentiletti "/>
				<xs:enumeration value="Albacete CD"/>
				<xs:enumeration value="Alberto Jiménez"/>
				<xs:enumeration value="Alberto de la Bella"/>
				<xs:enumeration value="Alexander Mesa"/>
				<xs:enumeration value="Ballou Jean"/>
				<xs:enumeration value="CD Tenerife"/>
				<xs:enumeration value="Daniel Hernández"/>
				<xs:enumeration value="Daniel Torres"/>
				<xs:enumeration value="David Omar Rodríguez"/>
				<xs:enumeration value="Diego Hernández"/>
				<xs:enumeration value="Ezequiel Araujo"/>
				<xs:enumeration value="Ezequiel Gorosito"/>
				<xs:enumeration value="Filip Malbašić"/>
				<xs:enumeration value="Francisco García"/>
				<xs:enumeration value="Francisco Montañés"/>
				<xs:enumeration value="Gabriel Martín"/>
				<xs:enumeration value="Héctor Hernández"/>
				<xs:enumeration value="Iñigo Ruiz de Galarreta"/>
				<xs:enumeration value="Javi Castellano"/>
				<xs:enumeration value="Javier Acuña"/>
				<xs:enumeration value="Jesús Manuel Santana"/>
				<xs:enumeration value="José Antonio Caro"/>
				<xs:enumeration value="José Manuel García"/>
				<xs:enumeration value="Juan Torres Ruiz"/>
				<xs:enumeration value="Luis Jesús Pérez"/>
				<xs:enumeration value="Luis Milla"/>
				<xs:enumeration value="Néstor Susaeta"/>
				<xs:enumeration value="Rafael Mir"/>
				<xs:enumeration value="Raúl Fernández-Cavada"/>
				<xs:enumeration value="Roman Zozulia"/>
				<xs:enumeration value="Rubén Castro"/>
				<xs:enumeration value="Samuel Geoffroy"/>
				<xs:enumeration value="Slavoljub Srnić"/>
				<xs:enumeration value="Sulleyman Muntari"/>
				<xs:enumeration value="Tomas Pekhart"/>
				<xs:enumeration value="UD Las Palmas"/>
				<xs:enumeration value="Uroš Račić"/>
				<xs:enumeration value="Álvaro Arroyo"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== rafaelgonzalezfrancisco/IFCD0210/MF0491-3 CLIENTE/UF1841/E2/equiposdefutbol - copia.xml
<?xml version="1.0" encoding="UTF-8"?>
<equiposdefutbol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/IFCD0210/MF0491-3%20CLIENTE/UF1841/E2/equiposdefutbol.xsd">
	<equipo>
		<nombre>CD Tenerife</nombre>
		<ciudad>S/C de Tenerife</ciudad>
		<jugadores>
			<jugador posicion="portero">
				<nombre>Daniel Hernández</nombre>
				<nacionalidad>venezolana</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>Luis Jesús Pérez</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>Héctor Hernández</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>Samuel Geoffroy</nombre>
				<nacionalidad>francesa</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>Alberto Jiménez</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Luis Milla</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Jesús Manuel Santana</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Uroš Račić</nombre>
				<nacionalidad>servia</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Francisco Montañés</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Filip Malbašić</nombre>
				<nacionalidad>servia</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>José Manuel García</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Alexander Mesa</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
		</jugadores>
	</equipo>
	<equipo>
		<nombre>UD Las Palmas</nombre>
		<ciudad>Las Palmas de Gran Canaria</ciudad>
		<jugadores>
			<jugador posicion="portero">
				<nombre>Raúl Fernández-Cavada</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>Alberto de la Bella</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>David García</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>David Omar Rodríguez</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>Juan Torres Ruiz</nombre>
				<nacionalidad>colombiana</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Javi Castellano</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Iñigo Ruiz de Galarreta</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Slavoljub Srnić</nombre>
				<nacionalidad>servia</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Gabriel Martín</nombre>
				<nacionalidad>argentina</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Rubén Castro</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Tomas Pekhart</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Ezequiel Araujo</nombre>
				<nacionalidad>argentina</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Rafael Mir</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
		</jugadores>
	</equipo>
	<equipo>
		<nombre>Albacete CD</nombre>
		<ciudad>Albacete</ciudad>
		<jugadores>
			<jugador posicion="portero">
				<nombre>José Antonio Caro</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>Álvaro Arroyo</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>Francisco García</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>Ezequiel Gorosito</nombre>
				<nacionalidad>argentina</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre> Juan Gentiletti </nombre>
				<nacionalidad>italana</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Sulleyman Muntari</nombre>
				<nacionalidad>francesa</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Néstor Susaeta</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Daniel Torres</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="centrocampista">
				<nombre>Diego Hernández</nombre>
				<nacionalidad>argentina</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Ballou Jean</nombre>
				<nacionalidad>francesa</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Roman Zozulia</nombre>
				<nacionalidad>argentina</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Javier Acuña</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
		</jugadores>
	</equipo>
</equiposdefutbol>
